- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_MUSHROOM_00C66A503 }}
    action: "upload"
    app_location: "/"        # where your index.html is
    output_location: "/"      # NO build folder, just use root
    skip_app_build: true      # <- important: disables Oryx build
    github_id_token: ${{ steps.idtoken.outputs.result }}
